version: '1.0.0.{build}'

configuration: Release

assembly_info:
    patch: false

environment:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    DOTNET_CLI_TELEMETRY_OPTOUT: 1

before_build:
    - appveyor-retry dotnet restore "src\RadarrCore.sln" -v Minimal
    
build_script:
    - dotnet build "src\RadarrCore.sln" -c Release

#test:
#    assemblies:
#        - '**\*.Test.dll'
  
pull_requests:
    do_not_increment_build_number: true

#only_commits:
#    files:
#        - src/
#        - appveyor.yml