version: '1.0.0.{build}'

configuration: Release

environment:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    DOTNET_CLI_TELEMETRY_OPTOUT: 1

before_build:
    - appveyor-retry dotnet restore "src\" -v Minimal
    
build_script:
    - dotnet build "src\" -c Release

test:
    assemblies:
        - 'src\**\*.Test.dll'

cache:
    - '%USERPROFILE%\.nuget\packages'
  
pull_requests:
    do_not_increment_build_number: true

#only_commits:
#    files:
#        - src/
#        - appveyor.yml